(()=>{
'use strict';if(window.__NADENA_PORTAL_INBOX_V1__)return;window.__NADENA_PORTAL_INBOX_V1__=true;
const URL='https://ojhaeccyulyrwoxgeurf.supabase.co';const KEY='sb_publishable_JZH6Ker5-yZoNY6sQFhVTA_YKnImI3z';const SESSION_KEY='nadena_games_session_v1';let items=[],busy=false,last=0;
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}function token(){return String(session()?.access_token||'')}
async function rpc(name,args={}){const t=token();if(!t)throw Error('unauthorized');const r=await fetch(`${URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,authorization:'Bearer '+t,'content-type':'application/json'},body:JSON.stringify(args),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.message||`HTTP ${r.status}`);return d}
function install(){if(document.getElementById('nadenaInboxButton'))return;const s=document.createElement('style');s.textContent=`#nadenaInboxButton{position:fixed;right:18px;bottom:18px;z-index:950;width:50px;height:50px;border:1px solid #5ea5ff;border-radius:15px;background:linear-gradient(145deg,#17203e,#273f7d);color:#fff;font-size:22px;box-shadow:0 12px 35px #0007;cursor:pointer}#nadenaInboxBadge{position:absolute;right:-5px;top:-6px;display:none;place-items:center;min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:#ef476f;color:#fff;border:2px solid #080b19;font:900 10px system-ui}#nadenaInboxModal{position:fixed;inset:0;z-index:1000;display:none;place-items:center;padding:14px;background:#02040bd8}#nadenaInboxModal.show{display:grid}.nadenaInboxCard{width:min(720px,96vw);max-height:88vh;display:flex;flex-direction:column;overflow:hidden;border:1px solid rgba(111,178,255,.4);border-radius:18px;background:#0c1227;color:#f1f5ff;box-shadow:0 30px 90px #000c}.nadenaInboxHead{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-bottom:1px solid #253252}.nadenaInboxHead h2{margin:0;font-size:20px}.nadenaInboxHead button{border:0;background:transparent;color:#fff;font-size:27px;cursor:pointer}.nadenaInboxList{display:grid;gap:10px;padding:14px;overflow:auto}.nadenaInboxMsg{padding:14px;border:1px solid #2a3657;border-radius:13px;background:#121b35;cursor:pointer}.nadenaInboxMsg.unread{border-color:#70c9ff;box-shadow:inset 4px 0 #70c9ff;background:#122642}.nadenaInboxMsg h3{margin:0 0 5px}.nadenaInboxMeta{font-size:11px;color:#9ca9c7}.nadenaInboxBody{margin-top:10px;white-space:pre-wrap;line-height:1.55;font-size:13px}.nadenaInboxEmpty{padding:30px;text-align:center;color:#9ca9c7}@media(max-width:700px){#nadenaInboxButton{right:10px;bottom:12px}}`;document.head.appendChild(s);const b=document.createElement('button');b.id='nadenaInboxButton';b.type='button';b.title='Nadena Nachrichten';b.innerHTML='✉️<span id="nadenaInboxBadge"></span>';b.onclick=open;document.body.appendChild(b);const m=document.createElement('div');m.id='nadenaInboxModal';m.innerHTML='<section class="nadenaInboxCard"><header class="nadenaInboxHead"><h2>✉️ Nachrichten von Nadena Games</h2><button id="nadenaInboxClose" type="button">×</button></header><div id="nadenaInboxList" class="nadenaInboxList"></div></section>';m.addEventListener('click',e=>{if(e.target===m)close()});document.body.appendChild(m);document.getElementById('nadenaInboxClose').onclick=close}
function badge(){const b=document.getElementById('nadenaInboxBadge');if(!b)return;const n=items.filter(x=>!x.read_at).length;b.textContent=n>99?'99+':String(n);b.style.display=n?'grid':'none'}
function render(){const host=document.getElementById('nadenaInboxList');if(!host)return;host.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='nadenaInboxEmpty';e.textContent='Keine Nachrichten vorhanden.';host.append(e);return}for(const m of items){const a=document.createElement('article');a.className='nadenaInboxMsg'+(m.read_at?'':' unread');const h=document.createElement('h3');h.textContent=m.subject||'Nachricht';const meta=document.createElement('div');meta.className='nadenaInboxMeta';meta.textContent='Nadena Games · '+new Date(m.created_at).toLocaleString('de-DE');const body=document.createElement('div');body.className='nadenaInboxBody';body.textContent=m.body||'';a.append(h,meta,body);a.onclick=async()=>{if(m.read_at)return;try{await rpc('nadena_mark_portal_message_read',{p_message_id:m.id});m.read_at=new Date().toISOString();a.classList.remove('unread');badge()}catch{}};host.append(a)}}
async function load(force=false){if(busy||!token()||(!force&&Date.now()-last<45000))return;busy=true;try{const rows=await rpc('nadena_get_portal_messages',{p_limit:80});items=Array.isArray(rows)?rows:[];last=Date.now();install();badge();if(document.getElementById('nadenaInboxModal')?.classList.contains('show'))render()}catch{}finally{busy=false}}
function open(){install();document.getElementById('nadenaInboxModal')?.classList.add('show');render();void load(true)}function close(){document.getElementById('nadenaInboxModal')?.classList.remove('show')}
function sync(){if(token()){install();void load(false)}else{document.getElementById('nadenaInboxButton')?.remove();document.getElementById('nadenaInboxModal')?.remove()}}
new MutationObserver(sync).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('focus',sync);window.addEventListener('storage',e=>{if(e.key===SESSION_KEY)sync()});setInterval(()=>{if(document.visibilityState==='visible')sync()},120000);setTimeout(sync,800);
})();